# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1321b080084006746aa030b1acf818e8b12bdfee924077a112cee06649ed5aa86617bff3ec3671239e725793ad6c60c8c3a0404fc6ec2cd3672921048c453d9d

test:
  secret_key_base: ce54b964333182c3fec99b75054574e154cd8305e930a61094b93b5bfe314fdb647faf07343dd225aa23222539074a72f1e5cdfa333e0618d3e906d29f55372c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
